DemoSite/Models/Umbraco/ListingPage.cs
using Umbraco.Cms.Core.Models.PublishedContent;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	public partial class ListingPage
	{
		public IEnumerable<IPublishedContent> ChildPages => Children.OfType<IPublishedContent>().Where(x => x.IsPublished());
	}
}

DemoSite/ViewComponents/BannerViewComponent.cs
using DemoSite.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Strings;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace DemoSite.ViewComponents
{
    public class BannerViewComponent : ViewComponent
    {
        private readonly IUmbracoContextAccessor _umbracoContextAccessor;
        public BannerViewComponent(IUmbracoContextAccessor umbracoContextAccessor)
        {
            _umbracoContextAccessor = umbracoContextAccessor;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (!_umbracoContextAccessor.TryGetUmbracoContext(out var umbracoContext) || umbracoContext == null)
            {
                return Content(string.Empty);
            }

            IPublishedContent? currentPage = umbracoContext.PublishedRequest?.PublishedContent;

            if (currentPage != null && currentPage is not IBannerProperties)
            {
                return Content(string.Empty);
            }

            BannerViewModel banner = new BannerViewModel
            {
                Title = currentPage.Value<string>("bannerTitle"),
                Content = currentPage.Value<IHtmlEncodedString?>("bannerContent"),
                Link = currentPage.Value<Link?>("bannerLink")
            };

            return View(banner);
        }
    }
}

DemoSite/ViewComponents/ListItemViewComponent.cs
using DemoSite.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Strings;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace DemoSite.ViewComponents
{
    public class ListItemViewComponent : ViewComponent
    {
        private readonly IUmbracoContextAccessor _umbracoContextAccessor;
        public ListItemViewComponent(IUmbracoContextAccessor umbracoContextAccessor)
        {
            _umbracoContextAccessor = umbracoContextAccessor;
        }

        public async Task<IViewComponentResult> InvokeAsync(IPublishedContent page)
        {
            if (page == null)
            {
                return Content(string.Empty);
            }

            ListItemViewModel listItem = new ListItemViewModel
            {
                Title = page.Name,
                Content = page.Value<IHtmlEncodedString>("bannerContent"),
                Link = page.Url()
            };

            return View(listItem);
        }
    }
}

DemoSite/Views/GridPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.GridPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Master.cshtml";
}

@await Component.InvokeAsync("Banner")

<div class="grid">
    <div class="container">
        <div class="row">
            <div class="col-12">
                @if (!string.IsNullOrWhiteSpace(Model.GridTitle))
                {
                    <h2 class="grid-title">@Model.GridTitle</h2>
                }

                <div class="grid-stack">
                    <!-- grid is populated by JavaScript (see frontend/ts/partials/grid-stack.ts) -->
                </div>

                <div class="grid-tray">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <button class="grid-tray-button gridTrayToggle">Open tray</button>

                                <div class="grid-tray-wrap">
                                    <div class="grid-stack-item">
                                        <div class="grid-stack-item-content">
                                            <opta-widget widget="competition_stats" competition="8" season="2024" template="normal" show_crests="true" show_images="false" show_ranks="true" show_player_rankings="true" show_team_rankings="true" visible_stats="goals,shots,shots_on_target,passes,cards_yellow,cards_red" limit="2" team_naming="brief" player_naming="initial" show_logo="true" show_title="true" breakpoints="310, 970, 1300" sport="football"></opta-widget>
                                        </div>
                                    </div>

                                    <div class="grid-tray-trash">Remove Widget</div>
                                </div>
                            </div><!-- col -->
                        </div><!-- row -->
                    </div><!-- container -->
                </div>
            </div><!-- row -->
        </div>
    </div>
</div>

DemoSite/Views/HomePage.cshtml
@inherits UmbracoViewPage<HomePage>
@{
    Layout = "Master.cshtml";
}

@await Component.InvokeAsync("Banner")

DemoSite/Views/ListingPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits UmbracoViewPage<ListingPage>
@{
    Layout = "Master.cshtml";
}

@await Component.InvokeAsync("Banner")

@if (Model.ChildPages != null && Model.ChildPages.Any())
{
    <section class="listing">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="visually-hidden">All Children of @Model.Name</h2>
                    <ul class="listing-list">
                        @foreach (IPublishedContent child in Model.ChildPages)
                        {
                            @await Component.InvokeAsync("ListItem", child)
                        }
                    </ul>
                </div><!-- col -->
            </div><!-- row -->
        </div><!-- container -->
    </section>
}

DemoSite/Views/Master.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = null;
}

@await Html.PartialAsync("Shared/_head")

@await Html.PartialAsync("Shared/_header")

<main>
    @RenderBody()
</main>

@await Html.PartialAsync("Shared/_footer")

DemoSite/Views/ReactPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.ReactPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = "Master.cshtml";
}

@await Component.InvokeAsync("Banner")

<div id="react-root"></div>

DemoSite/Views/TextPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits UmbracoViewPage<TextPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Master.cshtml";
}

@await Component.InvokeAsync("Banner")

@if (Model.ContentBlocks != null)
{
    @Html.GetBlockListHtml(Model.ContentBlocks)
}